# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=50)),
                ('firstname_lastname', models.CharField(default='0', max_length=50)),
                ('telephone', models.CharField(default='0', max_length=20)),
                ('email_address', models.CharField(default='0', max_length=50)),
                ('id_card_img_address', models.CharField(default='0', max_length=100)),
                ('verify_id', models.CharField(default='0', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('is_home_telephone_verified', models.BooleanField(default=False)),
                ('home_telephone', models.CharField(default='0', max_length=20)),
                ('address', models.CharField(default='0', max_length=100)),
                ('card_number', models.CharField(default='0', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
